config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "application#index"
    resources :posts do
      member do
        delete :remove_tag
        patch :toggle_status
      end
    end
  end

  resources :posts do
    resources :comments, only: %i(create)
  end

  resources :comments do
    resources :comments, only: %i(create)
  end

  get ":date/:slug", to: "home#post", as: :post_detail,
                     constraints: { :date => /\d{4}-\d{2}-\d{2}/ }

  get "author/:id/:name", to: "home#author_posts", as: :author, constraints: { :id => /\d+/ }

  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  authenticate :user do
    resources :subscriptions, only: :update
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tags = Post.tag_counts_on :tags
    if params[:tag]
      @posts = Post.published.tagged_with(params[:tag])
        .page(params[:page]).by_date
      @title = "Posts tagged ##{params[:tag]}"
    elsif params[:keywords]
      @posts = Post.published.search(params[:keywords])
        .page(params[:page])
      @title = "Posts matching '#{params[:keywords]}'"
    else
      @posts = Post.published.page(params[:page]).by_date
      @title = "Welcome to the Rails Blog"
    end
  end

  def post
    @post = Post.find_by!(published: params[:date],
                          slug: params[:slug],
                          status: "Published")
    @post.views_count += 1
    @post.save!
  end

  def author_posts
    @author = User.find(params[:id])
    @posts = @author.posts.published.page(params[:page]).by_date
    @title = "Posts by #{@author.name}"
    render :index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
= content_for :title, 'Home'
%h1 Rails Blog
%p.lead.mb-3.pt-3= @title

.posts
  - @posts.each do |post|
    .post-item{:id => "#{dom_id(post)}"}
      .post-item-header
        %h4
          = link_to post.title, post_detail_path(post.published, post.slug), class: 'post-title'
        %small.help= post.created_at.to_s(:long)
      .post-item-content
        = truncate(post.content.to_plain_text, length: 300)
      .post-item-footer
        %span.fw-normal
          By #{link_to post.author.name, author_page(post), class: 'link-success'}
        = render 'posts/post_tags', post: post
  %br/
  = will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

- content_for :sidebar do
  %h5 Popular Posts

  - Post.popular.each do |post|
    = render 'posts/post_card', post: post

  - if @tags
    %h5.mt-4 Tags
    = render 'posts/tag_cloud', tags: @tags

app/views/home/post.html.haml
%article.post{:id => "#{dom_id(@post)}"}
  = render 'posts/post_details', post: @post

  - comments = @post.comments.select(&:persisted?)
  - if comments.any?
    %h4.mt-4 Comments
  .comments{:id => "#{dom_id(@post)}_comments"}
    = render comments

  .mt-4
  = render 'comments/form', comment: @post.comments.build

= content_for :sidebar do
  .mb-3
    %p.subheader About the Author
    = render_user_profile(@post.author) do
      = render 'subscriptions/links', author: @post.author

  - similar_posts = @post.similar_posts

  - if similar_posts.any?
    %h5 Similar Posts
    - @post.similar_posts.each do |post|
      = render 'posts/post_card', post: post

  - else
    %h5 Popular Posts
    - Post.popular.each do |post|
      = render 'posts/post_card', post: post