config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "application#index"
    resources :posts do
      member do
        delete :remove_tag
        patch :toggle_status
      end
    end
  end

  resources :posts do
    resources :comments, only: %i(create)
  end

  resources :comments do
    resources :comments, only: %i(create)
  end

  get ":date/:slug", to: "home#post", as: :post_detail,
                     constraints: { :date => /\d{4}-\d{2}-\d{2}/ }

  get "author/:id/:name", to: "home#author_posts", as: :author, constraints: { :id => /\d+/ }

  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  authenticate :user do
    resources :subscriptions, only: :update
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :about, :avatar])
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_tags(post)
    render "admin/posts/tags", post: post
  end

  def author_page(post)
    author_path(post.author_id, post.author&.name&.parameterize)
  end

  def render_user_profile(user = current_user, &block)
    render "users/user", user: user, &block
  end
end

app/views/admin/application/index.html.haml
.d-flex.justify-content-between.align-items-center
  %h1 Your Posts
  = link_to 'New Post', new_admin_post_path, class: 'new'
.posts
  - @posts.each do |post|
    = render 'admin/posts/post', post: post

- content_for :sidebar do
  %p.subheader
    Your Profile
    = link_to 'Edit', edit_user_registration_path, class: 'fw-bold link-info float-end text-decoration-none small'
  = render_user_profile

  %h5 Stats
  %table.table.text-left.table-sm
    %tbody
      %tr
        %th Subscribers
        %td= current_user.subscribers.count
      %tr
        %th Posts
        %td= current_user.posts.count
      %tr
        %th Total Views
        %td= current_user.posts.sum(&:views_count)