config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "application#index"
    resources :posts do
      member do
        delete :remove_tag
        patch :toggle_status
      end
    end
  end

  resources :posts do
    resources :comments, only: %i(create)
  end

  resources :comments do
    resources :comments, only: %i(create)
  end

  get ":date/:slug", to: "home#post", as: :post_detail,
                     constraints: { :date => /\d{4}-\d{2}-\d{2}/ }

  get "author/:id/:name", to: "home#author_posts", as: :author, constraints: { :id => /\d+/ }

  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  authenticate :user do
    resources :subscriptions, only: :update
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  published   :date             default(Fri, 09 Sep 2022), not null
#  slug        :string           not null
#  status      :integer          default("Draft"), not null
#  title       :string           not null
#  views_count :bigint           default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  author_id   :bigint           not null
#
# Indexes
#
#  index_posts_on_author_id           (author_id)
#  index_posts_on_slug_and_published  (slug,published) UNIQUE
#  index_posts_on_views_count         (views_count)
#
# Foreign Keys
#
#  fk_rails_...  (author_id => users.id)
#
class Post < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search,
    against: :title,
    associated_against: {
      rich_text_content: [:body],
    },
    using: {
      tsearch: { prefix: true },
    }

  self.per_page = 6
  before_save :keep_last_four_tags

  belongs_to :author, class_name: "User"
  has_rich_text :content
  has_many :comments, as: :commentable

  enum status: {
         "Draft" => 0,
         "Published" => 1,
       }

  validates :status, inclusion: statuses.keys
  validates :title, :content, presence: true
  validates :title,
            uniqueness: { scope: :published,
                          message: "Post title should be unique for given date" }

  acts_as_taggable_on :tags

  scope :published, -> { where(:status => "Published") }
  scope :draft, -> { where(:status => "Draft") }
  scope :by_date, -> { order(created_at: :desc) }
  scope :popular, -> {
      published.where.not(views_count: 0)
        .order(views_count: :desc).limit(10)
    }

  def toggle_status!
    if status == "Draft"
      self.status = "Published"
    else
      self.status = "Draft"
    end
    save!
  end

  def keep_last_four_tags
    self.tag_list = tag_list.last(4)
  end

  def similar_posts
    find_related_tags.published.first(10)
  end

  before_create do
    unless slug
      self.slug = self.title&.parameterize
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :set_post, except: %i[new create]

  def new
    @post = Post.new
  end

  def show
  end

  def toggle_status
    @post.toggle_status!
    respond_to do |format|
      format.js
    end
  end

  def remove_tag
    tag = ActsAsTaggableOn::Tag.find(params[:tag_id])
    @tag_id = tag.id
    @post.tag_list.remove(tag.name)
    @post.save!
    head :ok
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.tag_list = processed_tags
    if @post.save
      flash[:notice] = "Post has been created."
      redirect_to admin_root_path
    else
      flash[:alert] = "Post has not been created."
      render :new
    end
  end

  def update
    @post.tag_list << processed_tags
    if @post.update(post_params)
      flash[:notice] = "Post has been updated."
      redirect_to admin_root_path
    else
      flash[:alert] = "Post has not been updated."
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post has been deleted."
    redirect_to admin_root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :status)
  end

  def processed_tags
    params[:post][:tag_list].split(",")
  end

  def set_post
    @post = Post.find(params[:id])

    unless current_user == @post.author
      flash[:notice] = "Only post author is allowed to perform this action"
      redirect_to admin_root_path
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_form.html.haml
= bootstrap_form_with(model: [:admin, post]) do |f|
  .field
    = f.text_field :title
  .field
    = f.rich_text_area :content
  .field
    = f.select :status, Post.statuses.keys
  .field
    = label_tag 'Tags'
    = render_tags post
    = text_field_tag 'post[tag_list]', "", class: 'form-control'
    %p.form-text.py-0.my-0 Separate tag names with commas. Maximum of 4 tags is allowed
    %p.form-text.py-0.my-0 If more than four tags are provided, the most recent four tags will be used
  .actions
    = f.primary

app/views/admin/posts/_post.html.haml
%body
  .post-item{:id => "#{dom_id(post)}"}
    %header.post-item-header
      %div
        %span.h3.me-sm-3= post.title
        %span.badge.bg-secondary.rounded= post.status
      %ul.actions
        %li= link_to 'Preview', admin_post_path(post), class: 'show'
        %li= link_to 'Edit', edit_admin_post_path(post), class: 'edit'
        %li= link_to 'Delete', admin_post_path(post), method: :delete, data: {confirm: 'Are you sure?'}, class: 'delete'
    .post-item-content
      = truncate(post.content.to_plain_text, length: 300)
    .post-item-footer
      = render_tags(post)
      = render 'admin/posts/status', post: post

app/views/admin/posts/_status.html.haml
.post-status
  - if post.status == 'Draft'
    = link_to 'Publish', toggle_status_admin_post_path(post), remote: true, |
      method: :patch, class: 'publish'                                      |
  - elsif post.status == 'Published'
    = link_to 'Unpublish', toggle_status_admin_post_path(post), remote: true, |
      method: :patch, class: 'unpublish'                                      |

app/views/admin/posts/_tags.html.haml
.tags
  - post.tags.each do |tag|
    .tag{:id => "#{dom_id(tag)}"}
      = link_to "<span></span>".html_safe,                    |
        remove_tag_admin_post_path(id: post, tag_id: tag.id), |
        method: :delete, remote: true,                        |
        class: "remove-tag", title: "Remove Tag"              |
      = tag.name

app/views/admin/posts/edit.html.haml
%h1 Edit Post
= render 'form', post: @post

app/views/admin/posts/new.html.haml
%h1 New Post
= render 'form', post: @post

app/views/admin/posts/show.html.haml
%h4.bg-light.px-3.py-2.border-bottom.mb-4 Post Preview
= render 'posts/post_details', post: @post

app/views/admin/posts/toggle_status.js.haml
var post = document.getElementById('#{"post_#{@post.id}"}');
post.outerHTML = "#{j render('admin/posts/post', post: @post)}";