config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "application#index"
    resources :posts do
      member do
        delete :remove_tag
        patch :toggle_status
      end
    end
  end

  resources :posts do
    resources :comments, only: %i(create)
  end

  resources :comments do
    resources :comments, only: %i(create)
  end

  get ":date/:slug", to: "home#post", as: :post_detail,
                     constraints: { :date => /\d{4}-\d{2}-\d{2}/ }

  get "author/:id/:name", to: "home#author_posts", as: :author, constraints: { :id => /\d+/ }

  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  authenticate :user do
    resources :subscriptions, only: :update
  end
end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_subscriptions_on_author_id              (author_id)
#  index_subscriptions_on_author_id_and_user_id  (author_id,user_id) UNIQUE
#  index_subscriptions_on_user_id                (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (author_id => users.id)
#  fk_rails_...  (user_id => users.id)
#
class Subscription < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :author_id
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_author

  def update
    Subscription.create!(user: current_user, author: @author)
    respond_to do |format|
      format.js
    end
  end

  private

  def set_author
    @author = User.find(params[:id])
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_links.html.haml
- if user_signed_in?
  - unless current_user.subscribed_to?(author)
    #subscription-link
      = link_to "Subscribe to this author's posts", subscription_path(id: author.id), class: 'btn btn-outline-info', remote: true, method: :patch,
        title: "You will receive an email whenever #{author.name} publishes a post"
- else
  %em.text-info
    = link_to 'Login', new_user_session_path,class: 'link-success'
    to subscribe to this author

app/views/subscriptions/update.js.erb
const subLinkEl = document.querySelector('#subscription-link');
subLinkEl.innerHTML =
  '<p class="text-success">You have successfully subscribed to this author</p>';